"""Changed Department primary key to dname

Revision ID: 0e4acd492be5
Revises: 154c74151437
Create Date: 2019-01-27 15:52:46.293872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4acd492be5'
down_revision = '154c74151437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_dname_key', 'department', type_='unique')
    op.add_column('program', sa.Column('department_dname', sa.String(length=40), nullable=True))
    # op.drop_constraint('program_department_university_fkey', 'program', type_='foreignkey')
    op.create_foreign_key(None, 'program', 'department', ['department_dname'], ['dname'])
    op.drop_column('program', 'department_university')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('department_university', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.create_foreign_key('program_department_university_fkey', 'program', 'department', ['department_university'], ['university'])
    op.drop_column('program', 'department_dname')
    op.create_unique_constraint('department_dname_key', 'department', ['dname'])
    # ### end Alembic commands ###
