"""Application Table

Revision ID: 154c74151437
Revises: 2b4754a836b3
Create Date: 2019-01-26 16:43:26.390753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154c74151437'
down_revision = '2b4754a836b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('university', sa.String(length=40), nullable=False),
    sa.Column('dname', sa.String(length=20), nullable=False),
    sa.Column('program', sa.String(length=10), nullable=False),
    sa.Column('dateOfApp', sa.DateTime(), nullable=True),
    sa.Column('termOfAdmission', sa.String(length=2), nullable=True),
    sa.Column('yearOfAdmission', sa.Integer(), nullable=True),
    sa.Column('admissionStatus', sa.String(length=10), nullable=True),
    sa.Column('dataSentToPaws', sa.String(length=3), nullable=True),
    sa.Column('applicant_email', sa.String(length=40), nullable=True),
    sa.Column('applicant_program', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['applicant_email'], ['applicant.email'], ),
    sa.ForeignKeyConstraint(['applicant_program'], ['program.program'], ),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
