"""Applicant Table

Revision ID: 2b4754a836b3
Revises: 2e68e79b2fba
Create Date: 2019-01-26 16:29:41.140791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4754a836b3'
down_revision = '2e68e79b2fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('lname', sa.String(length=20), nullable=False),
    sa.Column('address1', sa.String(length=40), nullable=True),
    sa.Column('address2', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('GREQ', sa.Integer(), nullable=True),
    sa.Column('GREV', sa.Integer(), nullable=True),
    sa.Column('GREA', sa.Float(), nullable=True),
    sa.Column('TOEFL', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('aid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant')
    # ### end Alembic commands ###
