"""Removied unique contstraint in program Table

Revision ID: 55bf1b0cee6f
Revises: 0e4acd492be5
Create Date: 2019-01-27 16:17:53.978859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bf1b0cee6f'
down_revision = '0e4acd492be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program', 'dname',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('program', 'university',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_constraint('program_dname_key', 'program', type_='unique')
    op.drop_constraint('program_university_key', 'program', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('program_university_key', 'program', ['university'])
    op.create_unique_constraint('program_dname_key', 'program', ['dname'])
    op.alter_column('program', 'university',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('program', 'dname',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
